body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ BEFORE OPENING A DISCUSSION ⚠️
        &nbsp;
        - Check the [wiki](https://github.com/jjjonesjr33/petlibro/wiki).
        - Search existing [issues](https://github.com/jjjonesjr33/petlibro/search?q=&type=issues) and [discussions](https://github.com/jjjonesjr33/petlibro/search?q=&type=discussions) (including closed ones!).
        &nbsp; 
  - type: markdown
    attributes:
      value: We need some information from you first to help us understand what is going on.
  - type: input
    id: model_name
    attributes:
      label: Device model name
      placeholder: ex. Granary Feeder
    validations:
      required: true
  - type: input
    id: model_number
    attributes:
      label: Device model number
      placeholder: ex. PLAF103
    validations:
      required: true
  - type: dropdown
    id: device_type
    attributes:
      label: Device type
      options:
        - Feeder
        - Fountain
        - Other
      default: 0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What is the issue?
      description: Also tell us, what did you expect to happen ?
      placeholder: Tell us what you see !
      value: "What seems to be the problem?"
    validations:
      required: true
  - type: textarea
    id: troubleshooting
    attributes:
      label: Troubleshooting
      description: Please review and provide any troubleshooting steps that you were able to perform, if any.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Home Assistant Logs
      description: Please include any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: python
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## ⚠️ NOTICE ⚠️
        &nbsp; 
        Before you submit this support request, please ensure you have checked the [wiki](https://github.com/jjjonesjr33/petlibro/wiki) as well as any [issues](https://github.com/jjjonesjr33/petlibro/search?q=&type=issues) and [discussions](https://github.com/jjjonesjr33/petlibro/search?q=&type=discussions), if relevant.

        *Please remember that this project is maintained by regular individuales **just like you**, so if you don't take the time to fill out the requested information, we may not be able to provide support.*
